GET http://localhost:3000/api/planets/
###
POST http://localhost:3000/api/planets/1/image
Content-Type: multipart/form-data;
boundary = IamSplitter

--IamSplitter
Content-Disposition: form-data; name="image";
filename = "test.png";
Content-Type: image/png

< images/test.png
--IamSplitter